# Generated by Django 5.2.1 on 2025-05-26 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_completedlesson_usercourseprofile_and_more'),
        ('final', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalquizresult',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.usercourseprofile'),
        ),
    ]
