# Generated by Django 5.2.1 on 2025-05-26 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_enrollment_is_completed'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourseprofile',
            name='enrollment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.enrollment'),
        ),
    ]
