# Generated by Django 5.2.1 on 2025-05-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_usercourseprofile_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourseprofile',
            name='user_rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
