# Generated by Django 5.2.1 on 2025-05-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_usercourseprofile_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourseprofile',
            name='progress_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
