# Generated by Django 5.2.1 on 2025-05-26 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_completedlesson_usercourseprofile_and_more'),
        ('final', '0003_remove_finalquizresult_profile'),
        ('quizzes', '0005_remove_quizresult_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourseprofile',
            name='completed_lessons',
        ),
        migrations.AlterUniqueTogether(
            name='usercourseprofile',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usercourseprofile',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='usercourseprofile',
            name='course',
        ),
        migrations.RemoveField(
            model_name='usercourseprofile',
            name='current_lesson',
        ),
        migrations.RemoveField(
            model_name='usercourseprofile',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='usercourseprofile',
            name='review',
        ),
        migrations.RemoveField(
            model_name='usercourseprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='CompletedLesson',
        ),
        migrations.DeleteModel(
            name='UserCourseProfile',
        ),
    ]
