# Generated by Django 5.2.1 on 2025-05-26 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_enrollment_is_completed'),
        ('profiles', '0002_usercourseprofile_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='profiles.usercourseprofile'),
        ),
    ]
