# Generated by Django 4.2.16 on 2025-05-20 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_finalquestion_finalexam_finalchoice_finaluseranswer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalchoice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='finalexam',
            name='course',
        ),
        migrations.RemoveField(
            model_name='finalquestion',
            name='course',
        ),
        migrations.AlterUniqueTogether(
            name='finalquizresult',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='finalquizresult',
            name='course',
        ),
        migrations.RemoveField(
            model_name='finalquizresult',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='finaluseranswer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='finaluseranswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='finaluseranswer',
            name='selected_choice',
        ),
        migrations.RemoveField(
            model_name='finaluseranswer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='FinalChoice',
        ),
        migrations.DeleteModel(
            name='FinalExam',
        ),
        migrations.DeleteModel(
            name='FinalQuestion',
        ),
        migrations.DeleteModel(
            name='FinalQuizResult',
        ),
        migrations.DeleteModel(
            name='FinalUserAnswer',
        ),
    ]
