# Generated by Django 5.2.1 on 2025-05-26 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_usercourseprofile_enrollment'),
        ('quizzes', '0005_remove_quizresult_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.usercourseprofile'),
        ),
    ]
