# Generated by Django 5.2.1 on 2025-05-26 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_quizresult_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='profile',
        ),
    ]
