# Generated by Django 5.2.1 on 2025-05-27 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_review_profile'),
        ('profiles', '0002_usercourseprofile_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourseprofile',
            name='user_rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_ratings', to='courses.review'),
        ),
    ]
