# Generated by Django 4.2.16 on 2025-05-18 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('notification_type', models.CharField(choices=[('answer', 'إجابة على سؤال'), ('course_completed', 'استكمال كورس'), ('course_enrolled', 'التحاق بكورس'), ('course_reviewed', 'تقييم كورس'), ('lesson_completed', 'استكمال درس'), ('lesson_question_answered', 'إجابة على سؤال درس'), ('lesson_watched', 'مشاهدة درس'), ('new_course', 'كورس جديد'), ('new_lesson', 'درس جديد'), ('new_quiz', 'اختبار جديد'), ('quiz_completed', 'استكمال اختبار'), ('quiz_reviewed', 'تقييم اختبار')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
